{{- if .Values.pdb.enabled }}
{{- $fullName := include "df-chart.fullname" . -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "df-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end}}}